version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/web/
hooks:
  AfterInstall:
   - location: script/setup.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: script/run.sh
     timeout: 300
     runas: ec2-user